security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_group_provider:
            entity:
                class: App\Entity\Group
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        login:
            # Utilisez ^/api/login_check (ou ^/api/login)
            pattern: ^/api/login_check
            stateless: true
            provider: app_group_provider # Il est recommandé de spécifier le provider
            json_login:
                check_path: /api/login_check
                username_path: email # Indique à Symfony d'utiliser la clé "email" du JSON
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        # Protection de toutes les autres routes API
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }